### ISSUE TITLE
After idling for a moment the OS seems to stop scheduling threads

### ISSUE THREAD

**Issue by Meulengracht** [Fadekraft/MollenOS#48]
Reasonable enough it shuts down the scheduling timer when entering idle thread to avoid rescheduling the idle thread and save resources, however it seems like no interrupts follow as well.. Which is weird since i need interrupts to wakeup the scheduler again. I'm thinking of building a threading log so I can see all thread activity

**Comment by Meulengracht** [comment]
This issue might be fixed now actually. Have to test this on real HW tho

**Comment by Fadekraft** [comment]
Fixed it, there was an issue with a list
