### ISSUE TITLE
LibC library fails to compile

### ISSUE THREAD

**Issue by Xoooo** [Fadekraft/MollenOS#57]
Link:
  D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"..\..\build\LibVs.dll" /
  NOLOGO LibC.lib LibCrt.lib /NODEFAULTLIB /MANIFEST:NO /DEBUG /PDB:"..\..\build\LibVs.pdb" /MAP /MAPINFO:EXPORTS /SUBS
  YSTEM:NATIVE /OPT:REF /OPT:ICF /LTCG /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\..\build\LibVs.lib" /MACHINE:X86 /SA
  FESEH /DLL LibVs\Release\\rtxx.obj
  LibVs\Release\delete.obj
  LibVs\Release\exception.obj
  LibVs\Release\Except32.obj
  LibVs\Release\Frame32.obj
  LibVs\Release\Unwind32.obj
  LibVs\Release\misc.obj
  LibVs\Release\new.obj
  LibVs\Release\rtti.obj
  LibVs\Release\typeinfo.obj
  LibVs\Release\undname.obj
  LibVs\Release\vectoreh.obj
  LibVs\Release\xcptfilter.obj
LINK : fatal error LNK1181: can not open input file“LibC.lib” [C:\Users\APP-3\Desktop\vs2013\MollenOS\clib\mscv\LibVs\LibVs.vcxproj]

**Comment by Meulengracht** [comment]
Thanks for reporting this, I'm sure it's wrong paths for the library includes (absolute paths instead of relative) -> I'll fix this in a few hours and update the repository
